config/routes.rb
Rails.application.routes.draw do
  resources :words, only: %i[index create]
  get 'word', to: 'words#word'
  root 'words#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
  validates :eng, uniqueness: true
  validates :eng, :rus, presence: true

  before_save :to_downcase

  def to_downcase
    self.eng = eng.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @word = Word.new
    @words = Word.order(updated_at: :desc)
    @next_word = Word.pluck(:id).sample
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to root_path
    else
      @words = Word.order(updated_at: :desc)
      render :index
    end
  end

  # we use sessions to help us not to show the same word too often
  def word
    if params.key?('hide')
      hide_word_for_a_week(params['hide'])
    end

    if session.fetch(:words, []).empty? || session[:lim] != params[:lim]
      word_ids = Word.where('hide_until < ? OR hide_until IS NULL', Time.current)
                     .order(created_at: :desc).pluck(:id)

      limit = params[:lim].to_i

      session[:words] = limit.positive? ? word_ids.first(limit) : word_ids
      session[:lim] = params[:lim]
    end

    word = session[:words].delete(session[:words].sample)

    @word = Word.find word
  end

  private

  def word_params
    params.require(:word).permit(:eng, :rus)
  end

  def hide_word_for_a_week(word_id)
    Word.find(word_id).update(hide_until: Time.current + 7.days)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li class ="#{'active' if params[:lim] == 'all'}" = link_to 'Single words', word_path(lim: 'all')
        li class ="#{'active' if params[:lim] == '10'}" = link_to 'Last 10 words', word_path(lim: 10)
        li class ="#{'active' if params[:lim] == '20'}" = link_to 'Last 20 words', word_path(lim: 20)
        li class ="#{'active' if params[:lim] == '30'}" = link_to 'Last 30 words', word_path(lim: 30)
      ul.nav.navbar-nav.navbar-right
        li
          a Words count: #{ Word.count}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyEnglish</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/words/index.html.slim
h2 Add new words to your dictionary by yourself!

= form_with model: @word do |f|
  = f.label 'In English'
  = f.text_field :eng

  br

  = f.label 'Translation'
  = f.text_field :rus

  br

  = f.submit 'Save a new word'

h2 Be free to memorize new words!

table.table.table-hovered
  tbody
    - @words.each do |word|
      tr
        td= @words.index(word) + 1
        td= word.eng
        td= word.rus
        td= word.created_at.strftime('%d/%m/%Y')

app/views/words/word.html.slim
.row.text-center.single-word
  .col-xs-12
    button.btn.btn-lg.btn-info = @word.eng
  .col-xs-12
    button.btn.btn-lg.btn-default.show-translation Show translation
  .col-xs-12.translation-div.hidden
    button.btn.btn-lg.btn-info.translation = @word.rus
  .col-xs-12
    = link_to 'Next word', word_path(lim: params[:lim]),
                           class: 'btn btn-lg btn-success next-word',
                           'data-turbolinks' => false,
                           data: { word_id: @word.id }
  .col-xs-12
    .checkbox
      label
        input type='checkbox'
        span Hide for a week